on:
  push:
    paths:
      - 'doc/**'
  workflow_dispatch:
name: CreatePDFs

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mkrakowitzer/actions-makepdfs@master
        if: github.ref == 'refs/heads/main'
        with:
          markdown_dir: doc
          output_dir: tmp

      - uses: actions/upload-artifact@v3
        with:
          name: manual-obce
          path: tmp/
